 function [Cand, Summary, Rpt] = findVariableAll2(Obj, Args)
            % Go over all files in the AllConsecutive property and search for variable sources.
            %   The function works by making the following calls:
            %   prepConsecutive
            %   findVaribleMS
            %   Next for variable candidates it runs:
            %   flagCorr
            %   and the plot* functions.
            % Input  : - A SearchMatchedSources object.
            %          * ...,key,val,...
            %            'Nvisit' - Number of sucessive visits to analyze.
            %                   Default is 2.
            %            'Nstep' - Number of steps between lists.
            %                   Default is 1.
            %            'Ncrop' - Number of sub images (crops).
            %                   Default is 24.
            %            'Plot' - Plot LCs of candidates.
            %                   Default is true.
            %            
            %            See code for additional arguments
            %
            % Output : - A structure array of variable candidates.
            %            Element per candidate.
            %          - Summary generated by findVariableMS
            % Author : Eran Ofek (Mar 2024)
            % Example: SMS = SearchMatchedSources;
            %          SMS.populateAllConsecutive;
            %          [Cand, Summary, Rpt] = SMS.findVariableAll('Nvisit',3,'Plot',true);


            arguments
                Obj
                Args.Nvisit    = 2;
                Args.Nstep     = 1;
                Args.Ncrop     = 24;
                
                Args.MinDet                = 2*(20-3);
                Args.SearchRadius          = 3;
                Args.SearchRadiusUnits     = 'arcsec';

                Args.MagField              = 'MAG_BEST';
                Args.MagErrField           = 'MAGERR_PSF'
                Args.LimMagQuantile        = 0.99;

                Args.RAField               = 'RA';
                Args.DecField              = 'Dec';

                Args.Plot logical          = true;
                Args.Report                = true;
            end

            RAD = 180./pi;

            Ncons = numel(Obj.AllConsecutive);
            Icand = 0;
            Cand  = [];
            for Icons=1:1:Ncons
                Ng = numel(Obj.AllConsecutive{Icons});
                for Ig=1:1:Ng
                    [Icons, Ncons, Ig, Ng]

                    for Icrop=1:1:Args.Ncrop
                        [Obj] = Obj.prepConsecutive(Icons, Ig, Icrop, 'Nvisit',Args.Nvisit,...
                                                                                      'Nstep',Args.Nstep,...
                                                                                                  'SearchRadius',Args.SearchRadius,...
                                                                                                  'SearchRadiusUnits',Args.SearchRadiusUnits,...
                                                                                                  'MagField',Args.MagField,...
                                                                                                  'MagErrField',Args.MagErrField,...
                                                                                                  'LimMagQuantile',Args.LimMagQuantile);
                        if ~isempty(Obj.MS)
                            %
                            if (median(diff(Obj.MS.JD)).*86400)>18 && max(diff(Obj.MS.JD))<30

                                %
                                [Flag, FlagInfo, Summary] = findVariableMS2(Obj);
    
                                FlagComb = FlagInfo.N(:)>Args.MinDet & Flag.FlagGood(:) & (Flag.PS(:) | Flag.RMS(:) | Flag.Poly(:) | Flag.RunMeanFilt(:));
        
                                if any(FlagComb)
                                    IndCand    = find(FlagComb);
                                    Ncand      = numel(IndCand);
    
                                    
    
                                    for I=1:1:Ncand
                                        IndSrc = IndCand(I);
    
                                        [FlagGood, ResPhotAstCorr] = flagCorr(Obj, IndSrc);
    
                                        if FlagGood
    
                                            RA  = median(Obj.MS.Data.(Args.RAField)(:,IndSrc), 1, 'omitnan');
                                            Dec = median(Obj.MS.Data.(Args.DecField)(:,IndSrc), 1, 'omitnan');
    
                                            Icand = Icand + 1;
                                            Cand(Icand).IndSrc          = IndSrc;
                                            Cand(Icand).NcandInSubImage = Ncand;
                                            Cand(Icand).Flag        = Flag;
                                            Cand(Icand).MS          = Obj.MS;
                                            Cand(Icand).FlagGood    = Flag.FlagGood(IndSrc);
                                            Cand(Icand).FlagPS      = Flag.PS(IndSrc);
                                            Cand(Icand).FlagRMS     = Flag.RMS(IndSrc);
                                            Cand(Icand).FlagPoly    = Flag.Poly(IndSrc);
                                            Cand(Icand).MaxPS       = Summary.MaxPS(IndSrc);
                                            Cand(Icand).MaxFreq     = Summary.MaxFreq(IndSrc);
                                            Cand(Icand).RA          = RA;
                                            Cand(Icand).Dec         = Dec;
        
                                            if Args.Plot
                                                
                                                % if Icand==1
                                                %     Fig = figure;
                                                % else
                                                %     clf;
                                                % end
                                                FigLC  = Obj.plotLC(IndSrc);
                                                FigRMS = Obj.plotRMS(IndSrc, 'NsigmaPredRMS',7);
                                                H = gca;
                                                H.YLim(1) = 1e-3;
                                                [FigPS, FigPh] = Obj.plotPS(IndSrc);
                                                drawnow;
                                                filepath = sprintf('~/Projects/Variables/M10T3/%.6f_%.6f_IND_%i_CropID_%i_%s.png',RA,Dec,IndSrc,Icrop,Obj.MS.FileName{1});
                                                saveas(FigLC, filepath);
    
                                                [SimbadURL]=VO.search.simbad_url(RA./RAD, Dec./RAD)
                                                SDSS_URL=VO.SDSS.navigator_link(RA./RAD, Dec./RAD);
                                                PS1_URL=VO.PS1.navigator_link(RA./RAD,Dec./RAD);
                                                PWD = pwd;
                                                cd('~/marvin/catalogs/GAIA/DR3/')
                                                AC=catsHTM.cone_search('GAIADR3',RA./RAD, Dec./RAD, 3,'OutType','AstroCatalog');
                                                cd(PWD)
    
                                                AbsMag = AC.Table.phot_bp_mean_mag - (5.*log10(1000./AC.Table.Plx)-5);
                                                Color  = AC.Table.phot_bp_mean_mag - AC.Table.phot_rp_mean_mag;
                                                fprintf('AbsMag: %5.2f    Color: %5.2f\n', AbsMag,Color);
    
                                                
    
                                                
                                                if Args.Report
                                                    if Icand==1
                                                        import mlreportgen.report.* 
                                                        import mlreportgen.dom.* 
                                                        Rpt = Report('~/Projects/Variables','pdf'); 
                                                        tp = TitlePage; 
                                                        tp.Title = 'Variables'; 
                                                        tp.Subtitle = '';
                                                        tp.Author = 'SearchMatchedSources/findVariableAll'; 
                                                        
                                                        append(Rpt,tp); 
                                                        append(Rpt,TableOfContents); 
        
                                                        ch1 = Chapter; 
                                                        ch1.Title = 'Variable candidates'; 
                                                    end
                                                    %---
                                                    
                                                    sec1 = Section; 
                                                    %br = PageBreak();
                                                    %append(sec1,br);
    
                                                    FlagsType = sprintf('%d %d %d %d', Flag.PS(IndSrc),  Flag.RMS(IndSrc), Flag.Poly(IndSrc), Flag.RunMeanFilt(IndSrc));
                                                    sec1.Title = sprintf('LAST J%s%s - %s',celestial.coo.convertdms(RA,'d','SH'), celestial.coo.convertdms(Dec,'d','SD'), FlagsType);
    
                                                    para = Text(sprintf('RA=%10.6f Dec=%10.6f\n Lim Mag: %5.1f\n MeanMag=%6.3f   StdMag=%6.3f\n AbsMag=%6.2f   Color=%6.2f\n',...
                                                        RA, Dec,...
                                                        median(quantile(Obj.MS.Data.(Args.MagField),0.99,2),1,'omitnan'),...
                                                        mean(Obj.MS.Data.(Args.MagField)(:,IndSrc), 1, 'omitnan'),...
                                                        std(Obj.MS.Data.(Args.MagField)(:,IndSrc), [], 1, 'omitnan'),...
                                                        AbsMag, Color)); 
                                                    append(sec1,para) 
    
                                                    fig = Figure(gcf);
                                                    fig.Snapshot.Height  = '6in'; 
                                                    fig.Snapshot.Width   = '7.5in'; 
                                                    fig.Snapshot.Caption = sprintf('');
                                                    append(sec1,fig); 
                                                    append(ch1, sec1);
    
                                                    %clf;  % close figure
                                                    close;
    
                                                end
    
                                                %web(SimbadURL.URL)
                                                if Flag.RunMeanFilt(IndSrc)
                                                'a'
                                                end
                                                
                                                % if Icand==300
                                                %     append(Rpt, ch1);
                                                % 
                                                %     close(Rpt)
                                                %     return;
                                                % end
                                            end
                                        end
                                    end
                                end
                                

                            end
                        end
                    end
                end
            end

            if Args.Report
                append(Rpt, ch1);
                
                close(Rpt)
                
                %rptview(Rpt)
            end


        end